# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Check for .env changes
      id: check-env-changes
      run: |
        echo "Changed files:"
        git diff --name-only ${{ github.event.before }} ${{ github.sha }}
        env_changed=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -c '^\.env$')
        echo "::set-output name=env_changed::${env_changed}"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      if: steps.check-env-changes.outputs.env_changed == '1'
      run: npm ci
    - name: Update .env file
      if: steps.check-env-changes.outputs.env_changed == '1'
      run: |
        echo "${{ secrets.ADVITIYA_PROD_ENV_FILE }}" > .env
    - name: Restart PM2
      if: steps.check-env-changes.outputs.env_changed == '1'
      run: pm2 restart AdvitiyaBackendAPI
